USE sakila;

# Task 1
# List the number of films per category.

SELECT c.name, COUNT(film_id) as count_film
FROM category as c
INNER JOIN film_category as fc
USING (category_id)
GROUP BY c.name;

# Task 2
# Retrieve the store ID, city, and country for each store.

SELECT store_id, city, country
FROM store as s
INNER JOIN address as a
USING (address_id)
INNER JOIN city as ci
USING (city_id)
INNER JOIN country as co
USING (country_id);

# Task 3
# Calculate the total revenue generated by each store in dollars.

SELECT sto.store_id as store, SUM(amount) as revenue
FROM store as sto
INNER JOIN staff as sta
USING (store_id)
INNER JOIN payment as pay
USING (staff_id)
GROUP BY sto.store_id;

# Task 4
# Determine the average running time of films for each category.

SELECT c.name, AVG(length) as running_time
FROM category as c
INNER JOIN film_category as fc
USING (category_id)
INNER JOIN film as fi
USING (film_id)
GROUP BY c.name
ORDER BY running_time DESC;

